### ISSUE TITLE
heated bed support

### ISSUE THREAD

**Issue by charlesbakervt** [Printrbot/Adaptrboard#1]
Hi all,
I am wondering if you have gotten this to work on a machine with a heated bed? 

I have been messing around with the skr mini e3 v1.2 on my Printrbot Simple Metal and it seems like most things are working except for the heated bed. If I try to turn on the heated bed, within 30 seconds I lose control of the printer, i.e. everything is locked up and I can't send commands. Eventually, maybe 60 seconds later, I get a message like: Offline (Error: SerialException: 'device reports readiness to read but returned no data (device disconnected or multiple access on port?)' @ comm.py:_readline:2823). Thanks for all the hard work you are doing to make this happen!

**Comment by abdrumm** [comment]
Im checking with Phil... Im embarrassed to report I havent even used it
with a heated bed. I do know Phil had me buy some separate heater board
because the one on the board wasnt as powerful as he liked for the Plus
that he has.... I'll get back to you on this if he responds :)

all my best
Brook

**Comment by charlesbakervt** [comment]
Fair enough. I am going to do some more troubleshooting this week and see what I can uncover. I will keep you posted on what I find out. Thanks again!

**Comment by drphil3d** [comment]
Yes, there are two simple things you must do. The Printrbot Play heated bed is more powerful than it needs to be. First you need to need to put a heat sink on the heated bed Mosfet. The SKR Mini requires a 1.0 Ohm heated bed, the Printrbot Play heated bed is about 0.7 Ohm, so we have to decrease the duty cycle to 170 which gives it an equivalent resistance of 1 ohm or so. The bed still heats plenty fast and will do over 100c. 
The otherwise inrush current draw is too great and causes the cpu to reset. 

There are two versions of the SKR Mini e3 - v1.0 which was an early version and v1.2 which has much better thermal design so this becomes less of an issue.

I recommend you use my firmware, It's been tested and fine tuned to make the probe as accurate as possible. 
https://github.com/Printrbot/Adaptrboard/releases/tag/v1  

Here is the source for that build
https://github.com/Printrbot/Adaptrboard/tree/master/Play/SKR%20Mini%20e3%20v1.2/Latest%20Build

**Comment by drphil3d** [comment]
You can also use an external solid state relay, but it's not really necessary and just adds another part that's hard to fit in the case and added complexity.

**Comment by charlesbakervt** [comment]
Thanks for the feedback! 

I actually have a Printrbot Simple Metal which has a 1.9 Ohm heated bed not 0.7 ohm. I finally got a chance to hook up my oscilloscope to some of the voltage lines and it looks like I am getting terrible signal bleed into the 5 volt line. When the heated bed is turned on with PWM enabled, I get this terrible PWM Square Wave showing up on the 5 volt line coming out to the USB. There must also be other factors at play because I cut the 5 volt line on the USB cord and with PWM enabled, the device would still stop responding ~60 seconds after turning on the heated bed. In contrast, if I disable bed pid and pwm for the heated bed, it will run stably with this usb cable that has its 5 volt line cut. I suppose I could just live with it like that but it feels super sketchy. 
Also, I used the ultra-scientific touch it test on the mosfets and they aren't hot when the cutoff happens. 
Any ideas? Maybe I have a bad power-supply or bad board?

**Comment by drphil3d** [comment]
What’s the rating and brand of the power supply are you using ? Yeah unfortunately the usb is not isolated on this board just like RAMPS so you end up powering the cpu via usb even when the mains power is turned off. I personally have had no issue with printing over usb with pid heated bed enabled.

 I think the board many not have the greatest power filtering and because were running on 12v instead of 24v which is what it’s optimized for use with there is 2X more current running through it at 12v. My theory is the high inrush current of the mosfet running at full power is likely causing noise from inductance to near by circuitry, the CPU is located quite close to the high current mosfets. . So reducing the duty cycle from 255 to say 220 or 200 I believe that should mitigate the problem.

I first started this project using the SKR mini e3 v1.0 which was an early release, with version 1.2 they switched from a 1oz to 2oz copper board which helped fix the cooling and I’m guessing also means thicker traces.

http://folgerforum.com/t/quick-and-simple-non-destructive-mod-for-a-data-only-no-power-usb-cable/2086

**Comment by charlesbakervt** [comment]
It is a CoolMax I-400 - supposedly 400 watt ATX power supply (definitely cheap). Theoretically, it should be capable of 25A on the 12 volt line but the voltage is definitely sagging to something more like 11.2 volts when under full load. 

The difference in driving the board with 12v vs 24v was my first thought. However, you are able to run a 0.9 ohm heated bed from 12 volt without major issue. I only need to drive a 1.9 ohm heated bed and it is very unstable even with duty cycle all the way down at 100. I may bite the bullet and look into getting an upgraded PSU to test things. The only other thing I can think is that maybe something on the SKR board itself is broken and preventing a stable ground voltage?  

Thanks again for all your help! I will report back if I figure out something new.
